Repository adopted-ember-addons/ember-data-model-fragments, pull requests merged in 2023-05, with the labels that each got.

#462 chore: drop node 12
  .github/workflows/ci.yml
  README.md
  config/ember-try.js
  package.json
  tests/dummy/config/targets.js
  yarn.lock
Labels: breaking

#464 Add support for ember-data 4.0 - 4.6
  .github/workflows/ci.yml
  README.md
  addon/array/fragment.js
  addon/array/stateful.js
  addon/attributes/array.js
  addon/attributes/fragment-array.js
  addon/attributes/fragment-owner.js
  addon/attributes/fragment.js
  addon/ext.js
  addon/fragment.js
  addon/record-data.js
  package.json
  tests/integration/dependent_state_test.js
  tests/integration/nested_test.js
  tests/integration/save_test.js
  tests/unit/array_property_test.js
  tests/unit/fragment_array_property_test.js
  tests/unit/fragment_array_test.js
  tests/unit/fragment_owner_property_test.js
  tests/unit/fragment_property_test.js
  tests/unit/fragment_test.js
  tests/unit/polymorphic_test.js
  tests/unit/serialize_test.js
  tests/unit/store_test.js
  yarn.lock
Labels: enhancement

#466 Fix glimmer render error when creating fragment arrays
  addon/array/stateful.js
  addon/attributes/array.js
  addon/attributes/fragment-array.js
  tests/integration/render_test.js
Labels: bug
